obj - m += pwmobchar.o

		   all : make -
	   C / lib / modules / $(shell uname - r) / build / M =
		   $(PWD) modules $(CC) testpwmobchar.c -
		   o test clean
	: make -
	  C / lib / modules / $(shell uname - r) / build / M =
			   $(PWD) clean rm test
