#!/bin/sh

module="scull"
device="scull"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number from /proc/devices
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# remove stale nodes and replace them
rm -f /dev/${device}[0-3]

# create nodes in /dev
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3

# link base nodes
ln -sf ${device}0 /dev/${device}

# give gid and perms
chgrp $group /dev/${device}[0-3]
chmod $mode  /dev/${device}[0-3]

