#!/bin/sh

module="twdrv"
device="twdrv"
mode="666"

if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default

sudo /sbin/insmod ./$module.ko $*

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

sudo rm -f /dev/${device}
sudo mknod /dev/${device}0 c $major 0
sudo ln -sf ${device}0 /dev/${device}
sudo chgrp $group /dev/${device}
sudo chmod $mode  /dev/${device}
